USE [master]
 

IF NOT EXISTS(SELECT * FROM sys.sysdatabases where name='Lacjam')
	BEGIN
	print 'CREATING DB'
	/****** Object:  Database [Lacjam]    Script Date: 18/08/2014 10:22:34 AM ******/
	CREATE DATABASE [Lacjam]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'Lacjam', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\Lacjam.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
	 LOG ON 
	( NAME = N'Lacjam_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL2012\MSSQL\DATA\Lacjam_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
	
	ALTER DATABASE [Lacjam] SET COMPATIBILITY_LEVEL = 110
	

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [Lacjam].[dbo].[sp_fulltext_database] @action = 'enable'
	end
	
	ALTER DATABASE [Lacjam] SET ANSI_NULL_DEFAULT OFF 
	

	ALTER DATABASE [Lacjam] SET ANSI_NULLS OFF 
	

	ALTER DATABASE [Lacjam] SET ANSI_PADDING OFF 
	

	ALTER DATABASE [Lacjam] SET ANSI_WARNINGS OFF 
	

	ALTER DATABASE [Lacjam] SET ARITHABORT OFF 
	

	ALTER DATABASE [Lacjam] SET AUTO_CLOSE OFF 
	

	ALTER DATABASE [Lacjam] SET AUTO_CREATE_STATISTICS ON 
	

	ALTER DATABASE [Lacjam] SET AUTO_SHRINK OFF 
	

	ALTER DATABASE [Lacjam] SET AUTO_UPDATE_STATISTICS ON 
	

	ALTER DATABASE [Lacjam] SET CURSOR_CLOSE_ON_COMMIT OFF 
	 

	ALTER DATABASE [Lacjam] SET CURSOR_DEFAULT  GLOBAL 
	 

	ALTER DATABASE [Lacjam] SET CONCAT_NULL_YIELDS_NULL OFF 
	 

	ALTER DATABASE [Lacjam] SET NUMERIC_ROUNDABORT OFF 
	 

	ALTER DATABASE [Lacjam] SET QUOTED_IDENTIFIER OFF 
	 

	ALTER DATABASE [Lacjam] SET RECURSIVE_TRIGGERS OFF 
	 

	ALTER DATABASE [Lacjam] SET  DISABLE_BROKER 
	 

	ALTER DATABASE [Lacjam] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	 

	ALTER DATABASE [Lacjam] SET DATE_CORRELATION_OPTIMIZATION OFF 
	 

	ALTER DATABASE [Lacjam] SET TRUSTWORTHY OFF 
	 

	ALTER DATABASE [Lacjam] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	 

	ALTER DATABASE [Lacjam] SET PARAMETERIZATION SIMPLE 
END	 

